### ISSUE TITLE
Parley succeed, pirate attack, and they retreat immediately?!!

### ISSUE THREAD

**Issue by WhiteGiverMa** [SonicTHI/SaveOurShip2Experimental#101]
https://github.com/SonicTHI/SaveOurShip2Experimental/assets/152406589/dff72815-4945-4ca3-9d4e-80df6530bb31

This is the video, and this kind of phenomenon (parley secceed then attack) **always** appears when I meet pirates.
As for they retreat immediately, this take places when I'm on the **Moon Base**.
[Player.log](https://github.com/SonicTHI/SaveOurShip2Experimental/files/13830181/Player.log)
this is the log.

**Comment by WhiteGiverMa** [comment]
This is the second time I report bugs, and I'm worring that it'll maybe make me a little annoying ε (๑> ₃ <) з

**Comment by SonicTHI** [comment]
You will find more bugs for sure. I am the only person working on this and other players barely report any bugs properly. The mod is in continuous development so bugs from new features such as this or revamped things like engine t/w are to be expected.

There is a chance for pirates to attack regardless if parleyed. Fixed in V96f6.
