### ISSUE TITLE
Sending animals into Crittersleep caskets can cause crash

### ISSUE THREAD

**Issue by h15588** [SonicTHI/SaveOurShip2Experimental#76]
build a Crittersleep caskets(8/32),anesthetize a tortoise, Right-click the tortoise under anesthesia(my english is poor,sorry)
modlist:
brrainz.harmony,ludeon.rimworld,ludeon.rimworld.royalty,ludeon.rimworld.ideology,ludeon.rimworld.biotech,unlimitedhugs.hugslib,murmur.walllight,kentington.saveourship2,void.charactereditor

[Player.log](https://github.com/SonicTHI/SaveOurShip2Experimental/files/11778564/Player.log)
[Crash_2023-06-17_100402313.zip](https://github.com/SonicTHI/SaveOurShip2Experimental/files/11778568/Crash_2023-06-17_100402313.zip)

**Comment by TerribleSpeller** [comment]
I can confirm this. Had the same issue, but don't know if it's due to mod conflict. 

Error log attached: 
[Player.log](https://github.com/SonicTHI/SaveOurShip2Experimental/files/12311456/Player.log)

This issue also applies to pawns, if a pawn is downed, interacting with them with a right click causes a crash as well.

**Comment by TerribleSpeller** [comment]
[Player.log](https://github.com/SonicTHI/SaveOurShip2Experimental/files/12311592/Player.log)

Log attached

**Comment by SonicTHI** [comment]
Fixed.
